# Dependencies
markdown:	redcarpet
# Permalinks
permalink:	/blog/:title

# Setup
baseurl:

title:		jayfor-lang
tagline:	'blog'
description:	'The official website for the Jayfor programming language'
url:		http://jayfor-lang.github.io
commentsystem:	google
disqus:		example

author:
  name:		'Felix Angell'
  url:		https://github.com/freefouran

paginate:	5

# Custom vars
icon:		/assets/images/icon.png
cover:		/assets/images/cover.jpg

social:
  - icon:	github
    url:	https://github.com/jayfor-lang
    desc:	Contribute

menu:
  - title:	Home
    url:	/

  - title:	About
    url:	/about

copyright:
  author:	The developers of Jayfor
  url:		http://jayfor-lang.io
  type_title:	All Rights Reserved
  type_url:	http://creativecommons.org/licenses/by-nc/2.5

# Google Analytics (add the UA Code, e.g.: UA-xxxxxxxx-1)
# kk will do m8
google_analytics:
