# Dependencies
markdown:	redcarpet
# Permalinks
permalink:	/blog/:title

# Setup
baseurl:

title:		ink-lang
tagline:	
description:	'The official website for the Ink programming language'
url:		http://ink-lang.github.io

author:
  name:		'Felix Angell'
  url:		https://github.com/freefouran

paginate:	5

# Custom vars
icon:		/assets/images/icon.png
cover:		/assets/images/cover.jpg

social:
  - icon:	github
    url:	https://github.com/ink-lang
    desc:	Contribute

copyright:
  author:	The developers of Ink
  url:		http://ink-lang.github.io
  type_title:	All Rights Reserved
  type_url:	http://creativecommons.org/licenses/by-nc/2.5

# Google Analytics (add the UA Code, e.g.: UA-xxxxxxxx-1)
# kk will do m8
google_analytics:
